### PR TITLE
Update Language.tr-TR.xaml

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by WXRIW** [comment]
Please resume all empty lines and keep the format correct!

**Comment by mikropsoft** [comment]
> Please resume all empty lines and keep the format correct!

I forgot that this is required for this repo and I edited it with the editor in the xml. I can't undo this operation because I'm out now. It would be a lot of work to do it again, but as far as I can see, this only affects the appearance. I don't think there will be a problem in the build process.

**Comment by WXRIW** [comment]
The format is very useful for checking the corresponding rows and checking the total number of rows. If it is lost, it will not be convenient for later updates and translation by other users.

**Comment by WXRIW** [comment]
It is suggested to do the translation in Visual Studio code with two xaml files opened, one is the source, and the other is the translation.

**Comment by mikropsoft** [comment]
> It is suggested to do the translation in Visual Studio code with two xaml files opened, one is the source, and the other is the translation.

Is there any script that will allow me to sync these?

**Comment by WXRIW** [comment]
> > It is suggested to do the translation in Visual Studio code with two xaml files opened, one is the source, and the other is the translation.
> 
> Is there any script that will allow me to sync these?

Sorry, I don't have any scripts. What I usually do is check the line number and find out whats changed. It is also very convenient by comparing commits using GitHub so you can find out whats changed between the latest version and the previous version!

**Comment by mikropsoft** [comment]
> > > It is suggested to do the translation in Visual Studio code with two xaml files opened, one is the source, and the other is the translation.
> > 
> > 
> > Is there any script that will allow me to sync these?
> 
> Sorry, I don't have any scripts. What I usually do is check the line number and find out whats changed. It is also very convenient by comparing commits using GitHub so you can find out whats changed between the latest version and the previous version!

I think it's better now

**Comment by WXRIW** [comment]
There are still some unwanted changes, please correct them, thank you so much.
image
Also, I will be uploading more strings in the next few days, and you can submit again after completing their translations. Thanks for your contribution! ❤️

**Comment by WXRIW** [comment]
New strings added!

**Comment by mikropsoft** [comment]
I think done now @WXRIW

**Comment by WXRIW** [comment]
Great work, but there are still some flaws in the formatting. It seems that you have completed the translation of the newly added strings, so the total number of lines in the XAML file should be the same, but now the original file has 1396 lines, and the tr-TR file has only 1349 lines. There must be something wrong, such as some places have blank lines, but the tr-TR file has no blank lines; some places should have two blank lines, but the tr-TR file has only one blank line.

I've made some changes to the file, please make sure to continue modifying based on the newly modified file. After the modification is completed, I think you can merge it.

**Comment by mikropsoft** [comment]
> Great work, but there are still some flaws in the formatting. It seems that you have completed the translation of the newly added strings, so the total number of lines in the XAML file should be the same, but now the original file has 1396 lines, and the tr-TR file has only 1349 lines. There must be something wrong, such as some places have blank lines, but the tr-TR file has no blank lines; some places should have two blank lines, but the tr-TR file has only one blank line.
> 
> I've made some changes to the file, please make sure to continue modifying based on the newly modified file. After the modification is completed, I think we will be ready to merge this PR.

Synchronized 👍

**Comment by WXRIW** [comment]
Excellent! I'll do the merge now, and it'll be available in version 4.3.1.

**Pull request merged**
