### PR TITLE
Update & partial rewrite fr-FR to fr-CA

### PR DESCRIPTION
**Pull request by R-953**
While improving and update the translation, I tried to make some of them meet the standards of Canadian French, the rest should be modified as June goes by. If this fix can be a satisfactory work for you, then I'm willing to continue on it. If not, that's also acceptable, let's just prevent nothing happened and roll back the name of the file to fr-FR
PS: Why in English ? No idea but I just saw almost everyone else is using English so I said to myself "why not"

### CODE REVIEW

**Comment by WXRIW** [comment]
Thank you for the translation. However, as you can see, the language options currently provided by Lyricify 4 only include language names and do not include specific regional languages. 

Supporting regionalized languages ​​is more difficult. Localization files currently use regionalized naming, and it may be possible to provide regionalized support for languages ​​in the future, but for now, we don't plan to support it. 

But you can keep this file locally for now, and it will come in handy if Lyricify provides localized language support in the future! Thanks again!

**Comment by R-953** [comment]
ahh I see🤝. So need I re-upload it as the name of fr-FR or redo some modifications to the file now ? Because the old one was out of date and I did the update as rewritings some of those words in that file. Well I personally think it's won't be a big problem, or if you think there's still necessary to redo the modified version, glad to help.

**Comment by WXRIW** [comment]
Yes, you can modify and update directly within the fr-FR file. When the usage of fr-FR and fr-CA are different, it is best to use the usage of fr-FR. You can make it as you like without restrictions. Thank you for your contribution and support!

**Comment by WXRIW** [comment]
Please keep `String.Window.TrackManagement.BasicInfo.Writer` as `Auteur` cause the official translation in Apple Music is Auteur.

**Comment by R-953** [comment]
👌I delete fr-CA and re-upload fr-FR, now I think it's done, please approve if there's still something need to be done.

**Comment by WXRIW** [comment]
One more suggestion, the translation of 'lyrics' should be 'paroles'. I just checked translations in iOS, and found it's paroles.

**Comment by R-953** [comment]
Yes you've the point. On spotify it's also read "paroles", I'll fix it right now.

**Comment by R-953** [comment]
Expressions incorrect of "Lyric" are all fixed to the right one "parole", is there anything else I'm supposed to do ? If yes, please go ahead and send it, if not, thanks all your patience and I think this pull can be closed. 🤝🤝🤝

**Comment by WXRIW** [comment]
You've done an excellent job.

For now, you can choose to merge the Pull Request now and add new translations in later PRs, or you can choose to add new translations in current PR and merge when ready!

**Comment by R-953** [comment]
Yes, I rechecked once and made sure that no more incorrect expression, you can merge it now🤝

**Comment by WXRIW** [comment]
Okay, I'll merge your contribution! Looking forward to future updates!

**Pull request merged**
